### ISSUE TITLE
FlowProcessingService not found.

### ISSUE THREAD

**Issue by apkelly** [AEVI-AppFlow/pos-android-sdk#246]
I get the following exception when trying to initiate a payment

```
PaymentClient initialised from io.aevitest

FlowException{errorCode='notInstalled', errorMessage='Processing service is not installed', originatingRequestId='null', target='null'}
	at com.aevi.sdk.flow.BaseApiClient.<clinit>(BaseApiClient.java:71)
	at com.aevi.sdk.pos.flow.PaymentApi.getPaymentClient(PaymentApi.java:72)
	at io.aevitest.PurchaseActivity.onCreate(PurchaseActivity.kt:63)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Here is the code I'm using to initiate a payment.

```
val paymentClient = PaymentApi.getPaymentClient(this.applicationContext)

paymentClient.initiatePayment(
    PaymentBuilder()
        .withAmounts(
            Amounts(100_00L, "AUD")
        )
        .withPaymentFlow("sale", "sale")
        .build()
).subscribe(
    { 
       println("FPS accepted Payment request")
       finish()
    },
    { throwable ->
        throwable.printStackTrace()
    }
)
```
Its the `paymentClient.initiatePayment` line of code that is throwing the exception, which I can see is performing the following check when called.

```
if (!isProcessingServiceInstalled(context)) {
    return Single.error(NO_FPS_EXCEPTION);
}
```

However, I can see the service is installed using the following command (and result)

`$ adb shell dumpsys activity services com.aevi`

```
ACTIVITY MANAGER SERVICES (dumpsys activity services)
  User 0 active services:
  * ServiceRecord{e2e4171 u0 com.aevi.sdk.fps/.FlowProcessingService}
    intent={cmp=com.aevi.sdk.fps/.FlowProcessingService}
    packageName=com.aevi.sdk.fps
    processName=com.aevi.sdk.fps
    baseDir=/data/app/~~fGbLd4IL4iw2Yh_8fyfAbA==/com.aevi.sdk.fps-PD23GdTgEoBuW4lu5Ksbug==/base.apk
    dataDir=/data/user/0/com.aevi.sdk.fps
    app=ProcessRecord{8521475 27921:com.aevi.sdk.fps/u0a327}
    allowWhileInUsePermissionInFgs=false
    recentCallingPackage=com.aevi.sdk.fps
    recentCallingUid=10327
    allowStartForeground=311
    startForegroundCount=1
    infoAllowStartForeground=[callingPackage: com.aevi.sdk.fps; callingUid: 10327; uidState: RCVR; intent: Intent { cmp=com.aevi.sdk.fps/.FlowProcessingService }; code:PACKAGE_REPLACED; tempAllowListReason:<broadcast:1000:android.intent.action.MY_PACKAGE_REPLACED,reason:,reasonCode:PACKAGE_REPLACED,duration:20000,callingUid:1000>; targetSdkVersion:28; callerTargetSdkVersion:28; startForegroundCount:0; bindFromPackage:null]
    isForeground=true foregroundId=7192 foregroundNoti=Notification(channel=FlowProcessingService shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
    createTime=-11m27s494ms startingBgTimeout=--
    lastActivity=-11m27s494ms restartTime=-11m27s494ms createdFromFg=false
    startRequested=true delayedStop=false stopIfKilled=false callStart=true lastStartId=1
```

I'm using v13 of the Developer Bundle, downloaded here `https://developer.aevi.com/downloads`, and the code is running on a Pixel 6 phone.

**Comment by apkelly** [comment]
Here is a screenshot from my phone, showing the installed and running service.

![Screenshot_20220803-181229](https://user-images.githubusercontent.com/2559953/182558715-840252d0-a97e-41bf-8e8b-0f01192b2a0d.png)

**Comment by apkelly** [comment]
I think I found the issue, on Android 11+ the list of services you can query has been restricted.

In order for the SDK to find the installed services I need to add the following to my AndroidManifest.xml file.

```
    <queries>
        <package android:name="com.aevi.sdk.fps" />
    </queries>
```
